$schema: http://json-schema.org/draft-04/schema#

id: project
title: Project
type: object
namespace: http://gdc.nci.nih.gov
program: '*'
project: '*'
category: administrative
description: Definitions for Project
additionalProperties: false
submittable: true
validators: null

required:
- submitter_id
- project_id

systemProperties:
- id
- project_id
- created_datetime
- updated_datetime

uniqueKeys:
- - id
- - project_id
  - submitter_id

links:
- backref: projects
  label: programs
  multiplicity: many_to_many
  name: programs
  required: false
  target_type: program

properties:
  cases:
    $ref: _definitions.yaml#/to_many
  compounds:
    $ref: _definitions.yaml#/to_many
  created_datetime:
    $ref: _definitions.yaml#/datetime
  gdc_attributes:
    type:
    - 'null'
    - object
  id:
    $ref: _definitions.yaml#/UUID
    systemAlias: node_id
  programs:
    $ref: _definitions.yaml#/to_many
  project_id:
    type: string
  submitter_id:
    type:
    - string
    - 'null'
  type:
    type: string
  updated_datetime:
    $ref: _definitions.yaml#/datetime
